# Generated by Django 4.2.2 on 2025-08-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date_payment",
            field=models.DateTimeField(verbose_name="дата оплаты"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="sum_payment",
            field=models.PositiveIntegerField(verbose_name="сумма оплаты"),
        ),
    ]
