# Generated by Django 4.2.2 on 2025-08-22 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Сourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_course",
                    models.CharField(max_length=50, verbose_name="название курса"),
                ),
                (
                    "image_course",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="materials/images/",
                        verbose_name="превью курса",
                    ),
                ),
                (
                    "description_course",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["title_course"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_lesson",
                    models.CharField(max_length=50, verbose_name="название урока"),
                ),
                (
                    "image_lesson",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="materials/images/",
                        verbose_name="превью урока",
                    ),
                ),
                (
                    "description_lesson",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "video_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="ссылка на видео урока"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="materials.сourse",
                        verbose_name="курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["title_lesson", "course", "owner"],
            },
        ),
    ]
