# Generated by Django 4.2.2 on 2025-08-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Сourse",
            new_name="Course",
        ),
    ]
