# Generated by Django 4.2.2 on 2025-08-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_rename_сourse_course"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["title_lesson", "course"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="owner",
        ),
    ]
